name: Trigger auto deployment for neurascan-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/neurascan-backend-AutoDeployTrigger-658c367e-e9e0-4fe9-9490-6f112ae524ce.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.NEURASCANBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.NEURASCANBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.NEURASCANBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/backend
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: neurascanacr2026.azurecr.io
          registryUsername: ${{ secrets.NEURASCANBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.NEURASCANBACKEND_REGISTRY_PASSWORD }}
          containerAppName: neurascan-backend
          resourceGroup: neurascan-rg
          imageToBuild: neurascanacr2026.azurecr.io/neurascan-backend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


